name: Generate Datas

on:
  schedule: # execute a cada 12 horas
    - cron: "0 */12 * * *"
  workflow_dispatch:

jobs:
  build:
    name: Atualizar dados e publicar
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v2
      
      - name: Instalar dependências
        run: npm install  # Ou qualquer outro comando para instalar dependências necessárias

      # Se necessário, adicione passos adicionais para gerar os dados ou executar outras tarefas

      - name: Snake Animation
        id: snake-gif
        uses: Platane/snk@master
        with:
          github_user_name: emersonjosedev
          svg_out_path: dist/github-contribution-grid-snake.svg

      - name: Adicionar animação da cobrinha ao README
        uses: gautamkrishnar/blog-post-workflow@master
        with:
          gh_token: ${{ secrets.GITHUB_TOKEN }}
          workflow_file: .github/workflows/generate-snake.yml
          commit_message: "Add snake animation to README"
