name: Generate Datas

on:
  schedule: # execute a cada 12 horas
    - cron: "0 */12 * * *"
  workflow_dispatch:

jobs:
  build:
    name: Atualizar dados e publicar
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v2
      
      - name: Instalar dependências
        run: npm install  # Ou qualquer outro comando para instalar dependências necessárias

      # Se necessário, adicione passos adicionais para gerar os dados ou executar outras tarefas

      - name: Snake Animation
        uses: Platane/snk@master
        with:
          github_user_name: emersonjosedev
          svg_out_path: dist/github-contribution-grid-snake.svg

      - name: Publicar em GitHub Pages
        uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: gh-pages # Ramo onde as páginas serão publicadas
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

